### PR TITLE
Fix: Add a core package to avoid hiding tasks in the docs

### LINKED ISSUE #87: Add a core package to avoid hiding tasks in the docs
### Expected Behavior

Docs don't support to have both tasks/triggers in the root package and in a sub package, whether it's:
- all tasks/triggers in the root package
- only tasks/triggers in sub packages

1. That's why these tasks/triggers should be moved (including the packages examples to update & tests if existing) to `io.kestra.plugin.nats.core`:
- plugin-nats/src/main/java/io/kestra/plugin/nats/Trigger.java
- plugin-nats/src/main/java/io/kestra/plugin/nats/NatsConnectionInterface.java
- plugin-nats/src/main/java/io/kestra/plugin/nats/Request.java
- plugin-nats/src/main/java/io/kestra/plugin/nats/Produce.java
- plugin-nats/src/main/java/io/kestra/plugin/nats/Consume.java
- plugin-nats/src/main/java/io/kestra/plugin/nats/SubscribeInterface.java
- plugin-nats/src/main/java/io/kestra/plugin/nats/RealtimeTrigger.java

2. Add the missing `package-info.java` in the `kv` package.

### Actual Behaviour

_No response_

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by aazam-gh**
### What changes are being made and why?

---
This PR closes #87 by restructuring the Nats plugin package organization to support proper documentation generation.

### How the changes have been QAed?

```yaml
id: simple-nats-test
namespace: company.team

description: Simple test of reorganized NATS plugin

tasks:
  - id: produce_message
    type: io.kestra.plugin.nats.core.Produce
    url: nats://host.docker.internal:4222
    username: kestra
    password: k3stra
    subject: kestra.test
    from:
      data: "Hello from reorganized NATS plugin!"
```

---

### Setup Instructions

---

### Contributor Checklist ✅

- [x] PR Title and commits follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Add a `closes #ISSUE_ID` or `fixes #ISSUE_ID` in the description if the PR relates to an opened issue.
- [x] Documentation updated (plugin docs from `@Schema` for properties and outputs, `@Plugin` with examples, `README.md` file with basic knowledge and specifics).
- [x] Setup instructions included if needed (API keys, accounts, etc.).
- [x] Prefix all rendered properties by `r` not `rendered` (eg: `rHost`).
- [x] Use `runContext.logger()` to log enough important infos where it's needed and with the best level (DEBUG, INFO, WARN or ERROR).

⚙️ **Properties**
- [x] Properties are declared with `Property<T>` carrier type, do **not** use `@PluginProperty`.
- [x] Mandatory properties must be annotated with `@NotNull` and checked during the rendering.
- [x] You can model a JSON thanks to a simple `Property<Map<String, Object>>`.

🌐 **HTTP**
- [x] Must use Kestra’s internal HTTP client from `io.kestra.core.http.client`

📦 **JSON**
- [x] If you are serializing response from an external API, you may have to add a `@JsonIgnoreProperties(ignoreUnknown = true)` at the mapped class level. So that we will avoid to crash the plugin if the provider add a new field suddenly.
- [x] Must use Jackson mappers provided by core (`io.kestra.core.serializers`)

✨ **New plugins / subplugins**
- [x] Make sure your new plugin is configured like mentioned [here](https://kestra.io/docs/plugin-developer-guide/gradle#mandatory-configuration).
- [x] Add a `package-info.java` under each sub package respecting [this format](https://github.com/kestra-io/plugin-odoo/blob/main/src/main/java/io/kestra/plugin/odoo/package-info.java) and choosing the right category.
- [x] Icons added in `src/main/resources/icons` in SVG format and not in thumbnail (keep it big):
  - `plugin-icon.svg`
  - One icon per package, e.g. `io.kestra.plugin.aws.svg`
  - For subpackages, e.g. `io.kestra.plugin.aws.s3`, add `io.kestra.plugin.aws.s3.svg`
    See example [here](https://github.com/kestra-io/plugin-elasticsearch/blob/master/src/main/java/io/kestra/plugin/elasticsearch/Search.java#L76).
- [x] Use `"{{ secret('YOUR_SECRET') }}"` in the examples for sensible infos such as an API KEY.
- [x] If you are fetching data (one, many or too many), you must add a `Property<FetchType> fetchType` to be able to use `FETCH_ONE`, `FETCH` and even `STORE` to store big amount of data in the internal storage.
- [x] Align the `"""` to close examples blocks with the flow id.

🧪 **Tests**
- [x] Unit Tests added or updated to cover the change (using the `RunContext` to actually run tasks).
- [x] Add sanity checks if possible with a YAML flow inside `src/test/resources/flows`.
- [x] Avoid disabling tests for CI. Instead, configure a local environment whenever it's possible with `.github/setup-unit.sh` (which can be executed locally and in the CI) all along with a new `docker-compose-ci.yml` file (do **not** edit the existing `docker-compose.yml`).
- [x] Provide screenshots from your QA / tests locally in the PR description. The goal here is to use the JAR of the plugin and directly test it locally in Kestra UI to ensure it integrates well.

📤 **Outputs**
- [x] Do not send back as outputs the same infos you already have in your properties.
- [x] If you do not have any output use `VoidOutput`.
- [x] Do not output twice the same infos (eg: a status code, an error code saying the same thing...).

### CODE REVIEW

**Comment by Malaydewangan09** [comment]
Just a small note for the future, if you could use GitHub Keywords when opening PRs to connect it to the proper issue (to automate the entire process a bit more), it would be super helpful to us. You can read a bit more about it [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) (I've added closing keyword for this particular issue).

**Comment by aazam-gh** [comment]
Hi @Malaydewangan09 I have addressed those changes.

**Review by fdelbrayelle — CHANGES_REQUESTED** [review]
@aazam-gh Could you duplicate the icon(s) in `src/main/resources/icons` for the new `.core` package please? 🙏

**Comment by aazam-gh** [comment]
@fdelbrayelle ready for review. addressed all changes!

File: src/main/java/io/kestra/plugin/nats/core/Request.java [hunk 1]
```diff
@@ -1,13 +1,14 @@
...
 import com.fasterxml.jackson.core.JsonProcessingException;
+import com.fasterxml.jackson.databind.ObjectMapper;
 import io.kestra.core.models.annotations.Example;
 import io.kestra.core.models.annotations.Plugin;
 import io.kestra.core.models.property.Data;
 import io.kestra.core.models.property.Property;
 import io.kestra.core.models.tasks.RunnableTask;
 import io.kestra.core.runners.RunContext;
-import io.kestra.core.serializers.JacksonMapper;
+import io.kestra.plugin.nats.NatsConnection;
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/nats/core/Request.java]: Unused import?

File: src/main/java/io/kestra/plugin/nats/package-info.java [hunk 2]
```diff
@@ -1,7 +1,8 @@
...
-    categories = PluginSubGroup.PluginCategory.MESSAGING
-)
+/**
+ * NATS plugin for Kestra.
+ * 
+ * This plugin provides integration with NATS messaging system, organized into sub-packages:
+ * - core: Core NATS messaging tasks and triggers
+ * - kv: NATS key-value storage operations
+ */
 package io.kestra.plugin.nats;
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/nats/package-info.java]: No please keep the file as it was before

**Review by fdelbrayelle — APPROVED** [review]
